language: node_js
node_js:
  - "6.11.2"

branches:
  only:
    - master

before_script:
  - npm install
  - npm run lint

script:
  - npm run build
  - echo ${NPMRC} > .npmrc
  - npm publish ./src/app/crud-table

after_success:
  - npm test -- --browsers PhantomJS --watch=false

notifications:
  email:
    on_failure: change
    on_success: change